#!/usr/bin/env python3
"""3-PE QR — streaming load, pipelined R^T+U^T rotation phase (+3 offset)."""

L = 12
O = 1
OFF = 3

VEC11 = O
ROT11_1 = O + 1
ROT11_2 = O + 2
VEC12 = O + L
ROT12_1 = VEC12 + 1
ROT12_2 = VEC12 + 2
VEC22 = ROT12_1 + L
ROT22_1 = VEC22 + 1

CAP_r11 = VEC12 + L
CAP_r12 = ROT12_1 + L
CAP_r13 = ROT12_2 + L
CAP_r22 = VEC22 + L
CAP_r23 = ROT22_1 + L
CAP_r33 = ROT22_1 + L

QR_CYCLES = CAP_r33 + 1
ROT_PIPE_CYCLES = QR_CYCLES + OFF

print("/* Auto-generated by gen_top_timing.py */")
print(f"localparam PE_LAT            = {L};")
print(f"localparam ROT_PIPE_OFFSET   = {OFF};")
print(f"localparam VEC_CYCLE11       = {VEC11};")
print(f"localparam VEC_CYCLE12       = {VEC12};")
print(f"localparam VEC_CYCLE22       = {VEC22};")
print(f"localparam ROT11_1           = {ROT11_1};")
print(f"localparam ROT11_2           = {ROT11_2};")
print(f"localparam ROT_CYCLE12_1     = {ROT12_1};")
print(f"localparam ROT_CYCLE12_2     = {ROT12_2};")
print(f"localparam ROT_CYCLE22_1     = {ROT22_1};")
print(f"localparam QR_CYCLES         = {QR_CYCLES};")
print(f"localparam ROT_PIPE_CYCLES   = {ROT_PIPE_CYCLES};")
print()
print(f"localparam CAP_r11 = {CAP_r11};")
print(f"localparam CAP_r12 = {CAP_r12};")
print(f"localparam CAP_r13 = {CAP_r13};")
print(f"localparam CAP_r22 = {CAP_r22};")
print(f"localparam CAP_r23 = {CAP_r23};")
print(f"localparam CAP_r33 = {CAP_r33};")
print(f"localparam CAP_u_r11 = {CAP_r11 + OFF};")
print(f"localparam CAP_u_r12 = {CAP_r12 + OFF};")
print(f"localparam CAP_u_r13 = {CAP_r13 + OFF};")
print(f"localparam CAP_u_r22 = {CAP_r22 + OFF};")
print(f"localparam CAP_u_r23 = {CAP_r23 + OFF};")
print(f"localparam CAP_u_r33 = {CAP_r33 + OFF};")
