#!/usr/bin/env python3
"""Generate golden vectors for cordic_pe testbench (bit-true reference)."""

import numpy as np

STAGES = 10
S_FRAC_BITS = 14
DATA_FRAC_BITS = 11
INT_BITS = 6
TOTAL_BITS = INT_BITS + DATA_FRAC_BITS
PE_LATENCY = STAGES + 2


def get_scaling_factor_csd(stages, s_frac_bits):
    ideal_K = np.prod([1.0 / np.sqrt(1 + 2 ** (-2 * i)) for i in range(stages)])
    n_val = int(np.round(ideal_K * (2 ** s_frac_bits)))
    csd = []
    temp_n = n_val
    while temp_n > 0:
        if temp_n % 2 == 0:
            csd.append(0)
            temp_n //= 2
        else:
            lookahead = (temp_n // 2) % 2
            if lookahead == 1:
                csd.append(-1)
                temp_n = (temp_n // 2) + 1
            else:
                csd.append(1)
                temp_n //= 2
    return csd


def wrap_signed(val, bits=TOTAL_BITS):
    mask = (1 << bits) - 1
    val &= mask
    if val >= (1 << (bits - 1)):
        val -= (1 << bits)
    return val


def shift_and_round(val, shift_amt):
    """Round half up — matches cordic_pe.v micro-rotation and CSD shifts."""
    if shift_amt <= 0:
        return wrap_signed(val << (-shift_amt))
    rounding_add = 1 << (shift_amt - 1)
    return wrap_signed((val + rounding_add) >> shift_amt)


def to_fixed(val, frac_bits=DATA_FRAC_BITS):
    scaled = int(np.floor(val * (2 ** frac_bits)))
    return wrap_signed(scaled)


def from_fixed(val, frac_bits=DATA_FRAC_BITS):
    return wrap_signed(val) / (2 ** frac_bits)


def apply_csd_scaling_hw(x_q, csd_array, s_frac_bits):
    """Hardware-style CSD scaling with round-half-up shifts."""
    result = 0
    for i, bit in enumerate(csd_array):
        if bit == 0:
            continue
        shift = s_frac_bits - i
        shifted = shift_and_round(x_q, shift)
        if bit == 1:
            result = wrap_signed(result + shifted)
        else:
            result = wrap_signed(result - shifted)
    return result


def cordic_vectoring_hw(x_q, y_q, stages, csd_array, s_frac_bits, quadrant_fix=True):
    x = wrap_signed(x_q)
    y = wrap_signed(y_q)
    if quadrant_fix and x < 0:
        x = wrap_signed(-x)
        y = wrap_signed(-y)

    d_bits = 0
    for i in range(stages):
        d = 0 if y >= 0 else 1
        if d:
            d_bits |= 1 << i

        x_shifted = shift_and_round(x, i)
        y_shifted = shift_and_round(y, i)

        if d:
            x = wrap_signed(x - y_shifted)
            y = wrap_signed(y + x_shifted)
        else:
            x = wrap_signed(x + y_shifted)
            y = wrap_signed(y - x_shifted)

    x_out = apply_csd_scaling_hw(x, csd_array, s_frac_bits)
    y_out = apply_csd_scaling_hw(y, csd_array, s_frac_bits)
    return x_out, y_out, d_bits


def cordic_rotation_hw(x_q, y_q, d_bits, stages, csd_array, s_frac_bits):
    x = wrap_signed(x_q)
    y = wrap_signed(y_q)

    for i in range(stages):
        d = (d_bits >> i) & 1
        x_shifted = shift_and_round(x, i)
        y_shifted = shift_and_round(y, i)

        if d:
            x = wrap_signed(x - y_shifted)
            y = wrap_signed(y + x_shifted)
        else:
            x = wrap_signed(x + y_shifted)
            y = wrap_signed(y - x_shifted)

    x_out = apply_csd_scaling_hw(x, csd_array, s_frac_bits)
    y_out = apply_csd_scaling_hw(y, csd_array, s_frac_bits)
    return x_out, y_out


def fmt_signed(val, bits=TOTAL_BITS):
    if val < 0:
        return f"-{bits}'sd{-val}"
    return f"{bits}'sd{val}"


def fmt_d_bits(d_bits, stages=STAGES):
    hex_w = (stages + 3) // 4
    return f"{stages}'h{d_bits:0{hex_w}x}"


def main():
    csd = get_scaling_factor_csd(STAGES, S_FRAC_BITS)

    vec_tests = [
        ("matrix1_row0", 6.5516178, 0.43827359),
        ("matrix2_row0", 1.02827641, 0.95816465),
        ("matrix4_row0", 2.04985484, -2.39385589),
        ("neg_x", -1.5, 0.75),
        ("small", 0.5, -0.25),
    ]

    print("// Auto-generated by gen_cordic_pe_vectors.py")
    print(f"// Q{INT_BITS}.{DATA_FRAC_BITS} ({TOTAL_BITS}-bit), round-half-up CORDIC")
    print(f"localparam PE_LATENCY = {PE_LATENCY};")
    print(f"localparam NUM_VEC_TESTS = {len(vec_tests)};")
    print()

    for idx, (name, xf, yf) in enumerate(vec_tests):
        xin = to_fixed(xf)
        yin = to_fixed(yf)
        xout, yout, d_bits = cordic_vectoring_hw(xin, yin, STAGES, csd, S_FRAC_BITS)
        print(
            f"// {name}: in=({xf}, {yf}) out=({from_fixed(xout):.6f}, {from_fixed(yout):.6f})"
        )
        print(
            f"vec_tests[{idx}] = '{{{fmt_signed(xin)}, {fmt_signed(yin)}, "
            f"{fmt_signed(xout)}, {fmt_signed(yout)}, {fmt_d_bits(d_bits)}}};"
        )

    vx = to_fixed(2.04985484)
    vy = to_fixed(-2.39385589)
    _, _, d_bits = cordic_vectoring_hw(vx, vy, STAGES, csd, S_FRAC_BITS)
    rx = to_fixed(0.43827359)
    ry = to_fixed(6.5516178)
    xout, yout = cordic_rotation_hw(rx, ry, d_bits, STAGES, csd, S_FRAC_BITS)
    print()
    print("localparam NUM_ROT_TESTS = 1;")
    print(f"// rotation using d=0x{d_bits:03x} from vectoring (2.0499, -2.3939)")
    print(
        f"rot_tests[0] = '{{{fmt_signed(rx)}, {fmt_signed(ry)}, {fmt_d_bits(d_bits)}, "
        f"{fmt_signed(xout)}, {fmt_signed(yout)}}};"
    )

    r11, r21 = 2.04985484, -2.39385589
    r12, r22 = 0.43827359, 1.02827641
    r13, r23 = 0.95816465, 0.7849

    q_r11, q_r21 = to_fixed(r11), to_fixed(r21)
    q_r12, q_r22 = to_fixed(r12), to_fixed(r22)
    q_r13, q_r23 = to_fixed(r13), to_fixed(r23)

    vx, vy, d_coupled = cordic_vectoring_hw(q_r11, q_r21, STAGES, csd, S_FRAC_BITS)
    rx1, ry1 = cordic_rotation_hw(q_r12, q_r22, d_coupled, STAGES, csd, S_FRAC_BITS)
    rx2, ry2 = cordic_rotation_hw(q_r13, q_r23, d_coupled, STAGES, csd, S_FRAC_BITS)

    print()
    print("// Coupled stream: vector (r11,r21) @0, rotate (r12,r22) @1, (r13,r23) @2")
    print(
        f"coupled_vec  = '{{{fmt_signed(q_r11)}, {fmt_signed(q_r21)}, "
        f"{fmt_signed(vx)}, {fmt_signed(vy)}, {fmt_d_bits(d_coupled)}}};"
    )
    print(
        f"coupled_rot1 = '{{{fmt_signed(q_r12)}, {fmt_signed(q_r22)}, "
        f"{fmt_signed(rx1)}, {fmt_signed(ry1)}}};"
    )
    print(
        f"coupled_rot2 = '{{{fmt_signed(q_r13)}, {fmt_signed(q_r23)}, "
        f"{fmt_signed(rx2)}, {fmt_signed(ry2)}}};"
    )


if __name__ == "__main__":
    main()
